In [1881]:
import numpy as np

In [1882]:
import math

In [1883]:
def normalize(data): 
    min_data = min(data) 
    max_data = max(data)
    data = np.array([( (d-min_data) / (max_data-min_data) ) for d in data])
    return data

In [1884]:
def normalize_2D(matrix): 
    min_matrix = matrix.min() 
    max_matrix = matrix.max()
    matrix = (matrix-min_matrix) / (max_matrix-min_matrix)
    return matrix
    #matrix = np.array([[( (y-min_data) / (max_data-min_data) ) for y in x] for x in matrix])

In [1885]:
p_select, n_clones, learn_rate, OMEGA, M_threshold = 0.5, 100, 0.5, 1.0, 0.8

In [1886]:
AG, AB = np.random.rand(5,3)*10, np.random.rand(10,3)*10

In [1950]:
AG

array([[6.33453018, 1.25058181, 5.33706963],
       [8.38359625, 7.55004981, 8.03988198],
       [9.00575246, 6.06211825, 3.65242211],
       [6.7081271 , 4.86421187, 0.43640812],
       [3.99438487, 3.33657761, 1.39972415]])

In [1951]:
AB

array([[6.58017137, 6.19409169, 8.35485914],
       [4.49867009, 8.37477192, 4.78001703],
       [8.34911463, 5.89512732, 0.38481066],
       [6.58613933, 7.83587821, 8.07769017],
       [7.1295375 , 2.20541962, 5.72443045],
       [1.00733977, 0.84546642, 8.02699627],
       [4.52116977, 8.68074098, 6.09550958],
       [1.42468793, 7.35705787, 5.1665517 ],
       [4.42445771, 1.21682798, 4.43059719],
       [4.11536068, 8.45526292, 0.34671322],
       [7.48486779, 7.69296401, 8.05878607],
       [6.9188323 , 3.53481574, 3.08041928],
       [5.56196119, 2.77099861, 3.5620773 ]])

In [1952]:
D = [[np.linalg.norm(ag-ab) for ab in AB] for ag in AG]

In [1953]:
D

[[5.797040889626663,
  7.377992582248024,
  7.082035190306694,
  7.1372569530027485,
  1.3014608265339378,
  5.981536706575932,
  7.685751264371109,
  7.837389691077019,
  2.114523215841372,
  9.0407853712461,
  7.087686890837343,
  3.2636795816824242,
  2.4615295784919353],
 [2.278195418617522,
  5.1380480071193295,
  7.831990447629416,
  1.820433664386863,
  5.958108010291055,
  9.967986961583895,
  4.46960679572642,
  7.531246765475719,
  8.295264517476806,
  8.844325360619692,
  0.910216832193432,
  6.547053403817696,
  7.131037059603782],
 [5.292804044468428,
  5.189761920277777,
  3.337116096515931,
  5.346377230450478,
  4.763142394909252,
  10.503568954989117,
  5.739106492301137,
  7.83849452953604,
  6.713468240445512,
  6.369519947524131,
  4.938500928946191,
  3.3271130071106323,
  4.764381282753115],
 [8.030368586407489,
  6.006052825909781,
  1.938630713139062,
  8.199687389382193,
  5.933796683659091,
  10.308555646620874,
  7.16757324670176,
  7.5168656402235925,
  5.87

In [1954]:
D=np.array(D)

In [1955]:
D

array([[ 5.79704089,  7.37799258,  7.08203519,  7.13725695,  1.30146083,
         5.98153671,  7.68575126,  7.83738969,  2.11452322,  9.04078537,
         7.08768689,  3.26367958,  2.46152958],
       [ 2.27819542,  5.13804801,  7.83199045,  1.82043366,  5.95810801,
         9.96798696,  4.4696068 ,  7.53124677,  8.29526452,  8.84432536,
         0.91021683,  6.5470534 ,  7.13103706],
       [ 5.29280404,  5.18976192,  3.3371161 ,  5.34637723,  4.76314239,
        10.50356895,  5.73910649,  7.83849453,  6.71346824,  6.36951995,
         4.93850093,  3.32711301,  4.76438128],
       [ 8.03036859,  6.00605283,  1.93863071,  8.19968739,  5.93379668,
        10.30855565,  7.16757325,  7.51686564,  5.8712947 ,  4.43013888,
         8.16736252,  2.96689834,  3.93256225],
       [ 7.95145152,  6.08802804,  5.15168878,  8.45908549,  5.46001693,
         7.68432229,  7.13358152,  6.07919351,  3.7235054 ,  5.22727524,
         8.68934285,  3.37882039,  2.73000847]])

In [1956]:
# Select the n highest affinity cells. 
# The cells with the least distance are first in the argsorted lists. 
H = [list(AB[d[0]]) for d in D.argsort()]

In [1957]:
H

[[7.129537497871077, 2.2054196158160497, 5.724430446975612],
 [7.48486779024827, 7.692964009770273, 8.058786074838167],
 [6.918832300196706, 3.5348157410256915, 3.080419283477715],
 [8.349114634802149, 5.895127315023051, 0.3848106560974296],
 [5.561961185278034, 2.770998610630894, 3.5620772997738257]]

In [1958]:
# Store the affinity values of the highest affinity cells. 
# H and HD map directly to one another. 
# So, the affinity of the first cell in H is the first value in HD. 
HD = [D[i][d[0]] for (i,d) in enumerate(D.argsort())]

In [1959]:
HD

[1.3014608265339378,
 0.910216832193432,
 3.3271130071106323,
 1.938630713139062,
 2.73000846672534]

In [1960]:
# Pair the HAF cells with HD affinities for sorting. 
Hab = [(a,b) for a,b in zip(H,HD)]

In [1961]:
Hab

[([7.129537497871077, 2.2054196158160497, 5.724430446975612],
  1.3014608265339378),
 ([7.48486779024827, 7.692964009770273, 8.058786074838167], 0.910216832193432),
 ([6.918832300196706, 3.5348157410256915, 3.080419283477715],
  3.3271130071106323),
 ([8.349114634802149, 5.895127315023051, 0.3848106560974296],
  1.938630713139062),
 ([5.561961185278034, 2.770998610630894, 3.5620772997738257],
  2.73000846672534)]

In [1962]:
Hab = sorted(Hab, key=lambda k:k[1])

In [1963]:
Hab

[([7.48486779024827, 7.692964009770273, 8.058786074838167], 0.910216832193432),
 ([7.129537497871077, 2.2054196158160497, 5.724430446975612],
  1.3014608265339378),
 ([8.349114634802149, 5.895127315023051, 0.3848106560974296],
  1.938630713139062),
 ([5.561961185278034, 2.770998610630894, 3.5620772997738257],
  2.73000846672534),
 ([6.918832300196706, 3.5348157410256915, 3.080419283477715],
  3.3271130071106323)]

In [1964]:
select = math.ceil(len(Hab)*p_select)

In [1965]:
select

3

In [1966]:
Hab = Hab[:select]

In [1967]:
Hab

[([7.48486779024827, 7.692964009770273, 8.058786074838167], 0.910216832193432),
 ([7.129537497871077, 2.2054196158160497, 5.724430446975612],
  1.3014608265339378),
 ([8.349114634802149, 5.895127315023051, 0.3848106560974296],
  1.938630713139062)]

In [1968]:
D = [hab[1] for hab in Hab]

In [1969]:
H = [hab[0] for hab in Hab] 

In [1970]:
H

[[7.48486779024827, 7.692964009770273, 8.058786074838167],
 [7.129537497871077, 2.2054196158160497, 5.724430446975612],
 [8.349114634802149, 5.895127315023051, 0.3848106560974296]]

In [1971]:
D

[0.910216832193432, 1.3014608265339378, 1.938630713139062]

In [1972]:
D_array = np.array(D)

In [1973]:
D_array

array([0.91021683, 1.30146083, 1.93863071])

In [1974]:
Dnorm = (D_array-D_array.min()) / (D_array.max() - D_array.min())

In [1975]:
Dnorm

array([0.        , 0.38043438, 1.        ])

In [1976]:
D = np.array([1])-Dnorm

In [1977]:
D

array([1.        , 0.61956562, 0.        ])

In [1978]:
N = D*n_clones

In [1979]:
N=N.astype(int)

In [1980]:
N

array([100,  61,   0])

In [1981]:
H = np.repeat(H,N,axis=0)

In [1982]:
H

array([[7.48486779, 7.69296401, 8.05878607],
       [7.48486779, 7.69296401, 8.05878607],
       [7.48486779, 7.69296401, 8.05878607],
       [7.48486779, 7.69296401, 8.05878607],
       [7.48486779, 7.69296401, 8.05878607],
       [7.48486779, 7.69296401, 8.05878607],
       [7.48486779, 7.69296401, 8.05878607],
       [7.48486779, 7.69296401, 8.05878607],
       [7.48486779, 7.69296401, 8.05878607],
       [7.48486779, 7.69296401, 8.05878607],
       [7.48486779, 7.69296401, 8.05878607],
       [7.48486779, 7.69296401, 8.05878607],
       [7.48486779, 7.69296401, 8.05878607],
       [7.48486779, 7.69296401, 8.05878607],
       [7.48486779, 7.69296401, 8.05878607],
       [7.48486779, 7.69296401, 8.05878607],
       [7.48486779, 7.69296401, 8.05878607],
       [7.48486779, 7.69296401, 8.05878607],
       [7.48486779, 7.69296401, 8.05878607],
       [7.48486779, 7.69296401, 8.05878607],
       [7.48486779, 7.69296401, 8.05878607],
       [7.48486779, 7.69296401, 8.05878607],
       [7.

In [1983]:
H = np.array([h-learn_rate*(h-AG) for h in H])

In [1984]:
H

array([[[6.90969898, 4.47177291, 6.69792785],
        [7.93423202, 7.62150691, 8.04933403],
        [8.24531012, 6.87754113, 5.85560409],
        [7.09649745, 6.27858794, 4.2475971 ],
        [5.73962633, 5.51477081, 4.72925511]],

       [[6.90969898, 4.47177291, 6.69792785],
        [7.93423202, 7.62150691, 8.04933403],
        [8.24531012, 6.87754113, 5.85560409],
        [7.09649745, 6.27858794, 4.2475971 ],
        [5.73962633, 5.51477081, 4.72925511]],

       [[6.90969898, 4.47177291, 6.69792785],
        [7.93423202, 7.62150691, 8.04933403],
        [8.24531012, 6.87754113, 5.85560409],
        [7.09649745, 6.27858794, 4.2475971 ],
        [5.73962633, 5.51477081, 4.72925511]],

       ...,

       [[6.73203384, 1.72800071, 5.53075004],
        [7.75656688, 4.87773471, 6.88215621],
        [8.06764498, 4.13376893, 4.68842628],
        [6.9188323 , 3.53481574, 3.08041928],
        [5.56196119, 2.77099861, 3.5620773 ]],

       [[6.73203384, 1.72800071, 5.53075004],
        [7.75

In [1985]:
H = np.reshape(H, (H.shape[0]*H.shape[1], H.shape[2]))

In [1986]:
H

array([[6.90969898, 4.47177291, 6.69792785],
       [7.93423202, 7.62150691, 8.04933403],
       [8.24531012, 6.87754113, 5.85560409],
       ...,
       [8.06764498, 4.13376893, 4.68842628],
       [6.9188323 , 3.53481574, 3.08041928],
       [5.56196119, 2.77099861, 3.5620773 ]])

In [1987]:
D = np.array([[np.linalg.norm(ag-ab) for ab in H] for ag in AG])

In [1988]:
D

array([[3.54384345, 7.10662443, 5.9651177 , ..., 3.42595871, 3.26367958,
        2.46152958],
       [3.6672882 , 0.45510842, 2.28964208, ..., 4.79615007, 6.5470534 ,
        7.13103706],
       [4.02464206, 4.78671948, 2.46925046, ..., 2.3815712 , 3.32711301,
        4.76438128],
       [6.27704301, 8.18917884, 5.98198223, ..., 4.52343831, 2.96689834,
        3.93256225],
       [6.15294134, 8.83743889, 7.10377746, ..., 5.2955192 , 3.37882039,
        2.73000847]])

In [1989]:
HD = [D[i][d[0]] for (i,d) in enumerate(D.argsort())]

In [1990]:
HD

[0.650730413266969,
 0.455108416096716,
 2.0115534022957684,
 2.966898341829545,
 2.73000846672534]

In [1991]:
H=[H[d[0]].tolist() for d in D.argsort()]

In [1992]:
H

[[6.732033836921801, 1.7280007122716832, 5.5307500379998515],
 [7.934232021214381, 7.621506910058812, 8.049334025794526],
 [7.096497446385302, 6.278587938002803, 4.247597097408993],
 [6.918832300196706, 3.5348157410256915, 3.080419283477715],
 [5.561961185278034, 2.770998610630894, 3.5620772997738257]]

In [1993]:
Hab = H

In [1994]:
Hab

[[6.732033836921801, 1.7280007122716832, 5.5307500379998515],
 [7.934232021214381, 7.621506910058812, 8.049334025794526],
 [7.096497446385302, 6.278587938002803, 4.247597097408993],
 [6.918832300196706, 3.5348157410256915, 3.080419283477715],
 [5.561961185278034, 2.770998610630894, 3.5620772997738257]]

In [1995]:
OMEGA # STORE ALL THE HIGH AFFINITY CELLS.

1.0

In [1996]:
M = Hab[:int(OMEGA*len(Hab))]

In [1997]:
M

[[6.732033836921801, 1.7280007122716832, 5.5307500379998515],
 [7.934232021214381, 7.621506910058812, 8.049334025794526],
 [7.096497446385302, 6.278587938002803, 4.247597097408993],
 [6.918832300196706, 3.5348157410256915, 3.080419283477715],
 [5.561961185278034, 2.770998610630894, 3.5620772997738257]]

In [1998]:
M = np.array(M)

In [1999]:
M

array([[6.73203384, 1.72800071, 5.53075004],
       [7.93423202, 7.62150691, 8.04933403],
       [7.09649745, 6.27858794, 4.2475971 ],
       [6.9188323 , 3.53481574, 3.08041928],
       [5.56196119, 2.77099861, 3.5620773 ]])

In [2000]:
# Clonal suppression. 
S = np.array([[np.linalg.norm(np.array(mx)-np.array(my)) for mx in M] for my in M])

In [2001]:
S

array([[0.        , 6.52088653, 4.74206277, 3.05017951, 2.51646319],
       [6.52088653, 0.        , 4.11806195, 6.5132323 , 7.02072451],
       [4.74206277, 4.11806195, 0.        , 2.98699763, 3.88946292],
       [3.05017951, 6.5132323 , 2.98699763, 0.        , 1.62988045],
       [2.51646319, 7.02072451, 3.88946292, 1.62988045, 0.        ]])

In [2002]:
S=normalize_2D(S)

In [2003]:
S

array([[0.        , 0.92880536, 0.67543781, 0.43445367, 0.35843355],
       [0.92880536, 0.        , 0.58655798, 0.92771512, 1.        ],
       [0.67543781, 0.58655798, 0.        , 0.42545433, 0.55399737],
       [0.43445367, 0.92771512, 0.42545433, 0.        , 0.23215274],
       [0.35843355, 1.        , 0.55399737, 0.23215274, 0.        ]])

In [2004]:
S=[[S[i][j] if j >= i+1 else 0 for j in range(S.shape[1])] for i in range(S.shape[0]-1)]

In [2005]:
S=np.array(S)

In [2006]:
np.argwhere(S>M_threshold)[:,1]

array([1, 3, 4])

In [2007]:
Mp=M[np.argwhere(S>M_threshold)[:,1]]

In [2008]:
Mp

array([[7.93423202, 7.62150691, 8.04933403],
       [6.9188323 , 3.53481574, 3.08041928],
       [5.56196119, 2.77099861, 3.5620773 ]])

In [2009]:
AB.shape

(13, 3)

In [2010]:
Mp.shape

(3, 3)

In [2011]:
AB=np.append(AB,Mp,axis=0)

In [2012]:
AB

array([[6.58017137, 6.19409169, 8.35485914],
       [4.49867009, 8.37477192, 4.78001703],
       [8.34911463, 5.89512732, 0.38481066],
       [6.58613933, 7.83587821, 8.07769017],
       [7.1295375 , 2.20541962, 5.72443045],
       [1.00733977, 0.84546642, 8.02699627],
       [4.52116977, 8.68074098, 6.09550958],
       [1.42468793, 7.35705787, 5.1665517 ],
       [4.42445771, 1.21682798, 4.43059719],
       [4.11536068, 8.45526292, 0.34671322],
       [7.48486779, 7.69296401, 8.05878607],
       [6.9188323 , 3.53481574, 3.08041928],
       [5.56196119, 2.77099861, 3.5620773 ],
       [7.93423202, 7.62150691, 8.04933403],
       [6.9188323 , 3.53481574, 3.08041928],
       [5.56196119, 2.77099861, 3.5620773 ]])