In [566]:
import numpy as np

In [567]:
import math

In [633]:
p_select, n_clones, learn_rate, OMEGA = 0.5, 2, 0.5, 1.0

In [607]:
AG, AB = np.random.rand(3,1)*10, np.random.rand(9,1)*10

In [608]:
AG

array([[5.75982327],
       [7.50343886],
       [8.38539479]])

In [609]:
AB

array([[5.83519715],
       [2.44375792],
       [2.07281713],
       [4.86374463],
       [3.57766174],
       [7.0755087 ],
       [3.67799244],
       [1.51243265],
       [5.29648763]])

In [610]:
D = np.array([[np.linalg.norm(ag-ab) for ab in AB] for ag in AG])

In [611]:
D

array([[0.07537388, 3.31606535, 3.68700614, 0.89607864, 2.18216153,
        1.31568543, 2.08183084, 4.24739063, 0.46333564],
       [1.66824171, 5.05968094, 5.43062173, 2.63969423, 3.92577712,
        0.42793016, 3.82544642, 5.99100621, 2.20695123],
       [2.55019764, 5.94163688, 6.31257767, 3.52165016, 4.80773305,
        1.3098861 , 4.70740236, 6.87296215, 3.08890716]])

In [612]:
# Select the n highest affinity cells. 
# The cells with the least distance are first in the argsorted lists. 
H = [AB[d[0]] for d in D.argsort()]

In [613]:
H

[array([5.83519715]), array([7.0755087]), array([7.0755087])]

In [576]:
# Store the affinity values of the highest affinity cells. 
# H and HD map directly to one another. 
# So, the affinity of the first cell in H is the first value in HD. 
HD = [D[i][d[0]] for (i,d) in enumerate(D.argsort())]

In [577]:
HD

[0.35842879118181337, 0.12346738703975868, 0.19073718551407115]

In [578]:
# Pair the HAF cells with HD affinities for sorting. 
Hab = [(a,b) for a,b in zip(H,HD)]

In [579]:
Hab

[(array([5.44489965]), 0.35842879118181337),
 (array([2.97419873]), 0.12346738703975868),
 (array([5.44489965]), 0.19073718551407115)]

In [580]:
Hab = sorted(Hab, key=lambda k:k[1])

In [581]:
Hab

[(array([2.97419873]), 0.12346738703975868),
 (array([5.44489965]), 0.19073718551407115),
 (array([5.44489965]), 0.35842879118181337)]

In [582]:
select = math.ceil(len(Hab)*p_select)

In [583]:
select

2

In [584]:
Hab = Hab[:select]

In [602]:
Hab

[(array([[4.38876359],
         [2.91246504],
         [4.30491779]]), array([3.55011542, 1.68583557])),
 (array([[5.62411405],
         [4.1478155 ],
         [5.54026825]]), array([2.11754868, 4.07525308]))]

In [603]:
D= [hab[1] for hab in Hab]

In [604]:
H

[array([[4.38876359],
        [2.91246504],
        [4.30491779]]), array([[5.62411405],
        [4.1478155 ],
        [5.54026825]])]

In [587]:
D

[0.12346738703975868, 0.19073718551407115]

In [588]:
N = (D/sum(D))*n_clones

In [589]:
N

array([0.78590446, 1.21409554])

In [590]:
N = [math.ceil(n) for n in N]

In [591]:
N

[1, 2]

In [600]:
H

[array([[4.38876359],
        [2.91246504],
        [4.30491779]]), array([[5.62411405],
        [4.1478155 ],
        [5.54026825]])]

In [614]:
H = np.array([h-learn_rate*(h-AG) for h in H])

In [615]:
H

array([[[5.79751021],
        [6.66931801],
        [7.11029597]],

       [[6.41766599],
        [7.28947378],
        [7.73045175]],

       [[6.41766599],
        [7.28947378],
        [7.73045175]]])

In [616]:
H = np.reshape(H, (H.shape[0]*H.shape[1]))

In [617]:
H

array([5.79751021, 6.66931801, 7.11029597, 6.41766599, 7.28947378,
       7.73045175, 6.41766599, 7.28947378, 7.73045175])

In [618]:
D = np.array([[np.linalg.norm(ag-ab) for ab in H] for ag in AG])

In [619]:
D

array([[0.03768694, 0.90949473, 1.3504727 , 0.65784271, 1.52965051,
        1.97062848, 0.65784271, 1.52965051, 1.97062848],
       [1.70592865, 0.83412085, 0.39314289, 1.08577287, 0.21396508,
        0.22701289, 1.08577287, 0.21396508, 0.22701289],
       [2.58788458, 1.71607679, 1.27509882, 1.96772881, 1.09592102,
        0.65494305, 1.96772881, 1.09592102, 0.65494305]])

In [624]:
HD = [D[i][d[0]] for (i,d) in enumerate(D.argsort())]

In [625]:
HD

[0.03768694020597074, 0.2139650793857779, 0.6549430475750837]

In [626]:
H = [H[d[0]] for d in D.argsort()]

In [628]:
H

[5.797510211277306, 7.289473779226569, 7.7304517474158745]

In [687]:
Hab = [(h,hd) for h,hd in zip(H,HD)]

In [714]:
Hab

[(5.797510211277306, 0.03768694020597074),
 (7.289473779226569, 0.2139650793857779),
 (7.7304517474158745, 0.6549430475750837)]

In [715]:
M = np.array(Hab[:int(OMEGA*len(Hab))])

In [716]:
M

array([[5.79751021, 0.03768694],
       [7.28947378, 0.21396508],
       [7.73045175, 0.65494305]])

In [717]:
M=M[M[:,1] < 0.7]

In [718]:
M = M[:,0]

In [719]:
M = np.array([np.array([m]) for m in M])

In [720]:
M

array([[5.79751021],
       [7.28947378],
       [7.73045175]])

In [721]:
# Clonal suppression. 
S = np.array([[np.linalg.norm(np.array(mx)-np.array(my)) for mx in M] for my in M])

In [722]:
S

array([[0.        , 1.49196357, 1.93294154],
       [1.49196357, 0.        , 0.44097797],
       [1.93294154, 0.44097797, 0.        ]])

In [723]:
Mp = np.argwhere(S > 0.5)

In [724]:
Mp

array([[0, 1],
       [0, 2],
       [1, 0],
       [2, 0]])

In [729]:
M[list(set(Mp.flatten()))]

array([[5.79751021],
       [7.28947378],
       [7.73045175]])

In [733]:
np.append(AB,M[list(set(Mp.flatten()))])

array([5.83519715, 2.44375792, 2.07281713, 4.86374463, 3.57766174,
       7.0755087 , 3.67799244, 1.51243265, 5.29648763, 5.79751021,
       7.28947378, 7.73045175])